# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

 version: 2
 updates:
   - package-ecosystem: "npm"
     directory: "/" # Location of package manifests
     schedule:
       interval: "monthly"
     reviewers:
       - "dev-rminds"
     assignees:
       - "dev-rminds"
     labels:
       - "Urgency: Low"
       - "dependencies"
     open-pull-requests-limit: 10
     target-branch: "develop"
     ignore:
       - dependency-name: "*"
         update-types: [ "version-update:semver-patch","version-update:semver-minor"]
